### ISSUE TITLE
Naming of the library

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/simulator#1]
What is your best naming ideas?🤔 

The use-cases for the library can be found here: https://github.com/asyncapi/community/issues/19#issuecomment-811121726

**Comment by NektariosFifes** [comment]
this is for the specification right?

**Comment by NektariosFifes** [comment]
@jonaslagoni 
Api-Analyzer
Api-Multimeter
Backendimeter
Fluffiest-robot
AsyncRobot
Stress-Tester

i might come up with smth better.

**Comment by jonaslagoni** [comment]
> @jonaslagoni this is for the specification right? or for the library

The general library I would say. Should the spec also have a separate name? 🤔

**Comment by NektariosFifes** [comment]
@jonaslagoni  no i was just wondering. so the spec will be pushed in the repo or in some issue?

**Comment by jonaslagoni** [comment]
> @jonaslagoni no i was just wondering. so the spec will be pushed in the repo or in some issue?

What you say we initially keep it all in one repo here, and decide later if it should be separated 😄 ?

**Comment by derberg** [comment]
what is wrong with `fluffy-robot` anyway?

**Comment by jonaslagoni** [comment]
> what is wrong with `fluffy-robot` anyway?

I mean, it does not really say anything about what the library is for 😆

**Comment by derberg** [comment]
>  it does not really say anything about what the library is for 

then add a description 🤷🏼 😄

**Comment by jonaslagoni** [comment]
> > it does not really say anything about what the library is for
> 
> then add a description 🤷🏼 😄

haha, okay @derberg suggest we keep the name 😆

**Comment by NektariosFifes** [comment]
@jonaslagoni  thing is there are already repos named fluffy-robot

**Comment by derberg** [comment]
it is all about simulation right? but simulation is long word, so what about the name that includes worked `mimic` or `imitate`

`asyncapimic`
`asyncapitate`

OMG, I'm so bad about coming up with names 🤦🏼 `asyncapitate` 🤦🏼

**Comment by NektariosFifes** [comment]
flAPI-bird

**Comment by hkaur008** [comment]
😃😂 actually , i think fluffy-robot doesn't convey anything but its cool and eye-catchy somehow

**Comment by NektariosFifes** [comment]
i think i got a nice one 
EventSalvo
salvo meaning : a simultaneous discharge of artillery or other guns in a battle.

**Comment by derberg** [comment]
@NektariosFifes I suggest you collect like 5 names you like the most out of all the proposals and set up easy voting for all, share it, give few days, and rename 😄

**Comment by derberg** [comment]
and out of curiosity proposal, why not just call it a `simulator` 😄

**Comment by NektariosFifes** [comment]
@derberg  this sound fine . the only problem is that probably multiple repos already have been named like that.

**Comment by derberg** [comment]
@NektariosFifes don't worry about that, we have `asyncapi/generator` and I bet many other orgs/users have it. So don't worry about that when you will be selecting these 5 or 3 or N names for voting.

**Comment by derberg** [comment]
closing this one as renaming was done
