### ISSUE TITLE
AsyncAPI Application simulation

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/simulator#16]
#### Reason/Context
A simulation library that can trigger events in your applications based on AsyncAPI definition(s). The main purpose is to stimulate your application(s) in a development environment (staging?). Use it for stress testing, hunting down concurrency problems, stimulating visual applications, finding scalability issues in your application, and more.

The general use-case:
- You provide one or more AsyncAPI files
- You decide which channel(s) and applications should be stimulated and with which parameters.
- The library simulates messages to the application(s) based on the parameters, in the given protocol described in the AsyncAPI file. 
- Inspect the application(s) and their state to figure out if errors occurred etc

**Required knowledge:**
You need to learn the basics of the AsyncAPI specification since it relies on the information in the provided documents. 

**Description**
I suggest focusing on the important parts of the use-case which are:
- Simulation scenarios
- Scaled simulations (how do you simulate something like 1 million users/requests)
- Others focus points?

Rabbit holes / be careful around these topics:
- Specifying the Simulation scenarios 
- Optimizing the code
- Supporting all protocols
- CLI for the library

Of course, these things are all suggestive and depend on what the user finds important. So never see any of these things as non-negotiable requirements and focus points.

**Comment by derberg** [comment]
Shouldn't this issue be closed?
