### ISSUE TITLE
React Statistics Library

### ISSUE THREAD

**Issue by NektariosFifes** [asyncapi/simulator#4]
#### Reason/Context

React library for visualizing statistics. Will be used for describing simulation results.
Any ideas?

Features 
| id | priority | feature |
| --- | --- | --- |
| #rc1 | Could Have| Progress bar with options to be streamed live results via Tcp socket |
|   #rc2      |      Must Have  |   One or multiple card-like  layouts to place statistics components for different scenarios. 
| #rc3 |  Could have | Requests per second graph |

Rules
| id |  Rule |
|--- | --- |
| #Rc1 | Preferably use function components and hooks |

**Comment by hkaur008** [comment]
Hey , I think I can contribute to this project , please direct me , how to get started .

**Comment by jonaslagoni** [comment]
Hey @hkaur008, thanks for taking an interest! As the library is still only getting started there is not much to do at the moment. As we have multiple people that want to help out we will focus on separating the responsibilities as fast as possible to allow parallel development. The best thing to do is to `watch` the repository, the project should get some traction within the next 2 weeks. Also, feel free to join our [slack channel](https://asyncapi.com/slack-invite) if you want to keep up to date with tooling development. But yeah, we definitely need an updated readme that clarifies this.

**Comment by hkaur008** [comment]
> Hey @hkaur008, thanks for taking an interest! As the library is still only getting started there is not much to do at the moment. As we have multiple people that want to help out we will focus on separating the responsibilities as fast as possible to allow parallel development. The best thing to do is to `watch` the repository, the project should get some traction within the next 2 weeks. Also, feel free to join our [slack channel](https://asyncapi.com/slack-invite) if you want to keep up to date with tooling development. But yeah, we definitely need an updated readme that clarifies this.

I can help in setting up readme, this would help me to remain aligned with the project and contribute to it more after setting up. If you don't mind!

**Comment by jonaslagoni** [comment]
> I can help in setting up readme, this would help me to remain aligned with the project and contribute to it more after setting up. If you don't mind!

That would be awesome! Thanks!

**Comment by NektariosFifes** [comment]
@hkaur008 

Hey,  we are just at the phase of putting our ideas in the correct order:
https://github.com/asyncapi/fluffy-robot/issues/14#issue-881839007
