### ISSUE TITLE
Basepath cli option does not propegate to AsyncAPI parser

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/simulator#45]
#### How to Reproduce
Changing [the ref path](https://github.com/asyncapi/fluffy-robot/blob/85f81eebae133ac7611c2ccd7336ac34ccda0b56/example-projects/game-processor/asyncapi.yaml#L20) to `$ref:  "./AsyncAPI/components/Parameters.yaml#/serverId"` 

For then to run the simulator with `simulator -f ./asyncapi.yaml -s ./scenario.yaml -b ./example-projects/game-processor`, I would expect all local references in the AsyncAPI file to be resolved using the provided base path.

Instead of throwing the following error:
```
ParserError: Error opening file "/Users/lagoni/Documents/AsyncAPI/fluffy-robot/AsyncAPI/components/Parameters.yaml" 
ENOENT: no such file or directory, open '/Users/lagoni/Documents/AsyncAPI/fluffy-robot/AsyncAPI/components/Parameters.yaml'
```

**Comment by NektariosFifes** [comment]
i will try to fix this now that i have more time

**Comment by NektariosFifes** [comment]
@jonaslagoni hello :) , is there any way for the async api parser to change the base bath for file references? Could that be an issue for a future feature in parser? If it is out of the scope of parser i will have to write smth to update the relative paths in the asyncApi file provided to the simulator.

**Comment by NektariosFifes** [comment]
ahh ok i found the path option in the parser that solves this
