### ISSUE TITLE
Desktop Application

### ISSUE THREAD

**Issue by NektariosFifes** [asyncapi/simulator#88]
#### Reason/Context

We could create a desktop application for the simulator.
- With it the user should be able to:
- Edit scenario file inside the app,
- View in a visualized interface the options to activate a particular scenario or operation that he has defined.

**Comment by NektariosFifes** [comment]
partially progressed by #94

**Comment by NektariosFifes** [comment]
@jonaslagoni  it would be nice if somehow we could automate a new desktop.Setup.exe file to be added to releases when a new major version comes out.

**Comment by ishaan812** [comment]
Hey, wasn't able to run the CLI but managed to run the docker compose and could follow the example code quite a bit since I have some work done with websockets and could follow the code pretty well this seems like an interesting project and I would love to contribute. Any updates on the GSOC status?

**Comment by NektariosFifes** [comment]
@ishaan812 hey you don't really need to use docker. i think it more convenient to install mongodb and mosquito in your pc. Then  
configure the connection to your mongo database.

**Comment by ishaan812** [comment]
How do I run just the CLI seperately to test it out. I prefer running it with docker unless there are some issues.

**Comment by NektariosFifes** [comment]
@ishaan812 simulator -f ./example-projects/game-processor/asyncapi.yaml -s ./example-projects/game-processor/scenario.yaml
while in the root directory. if not in the root directory you must specify the root directory with -b option

**Comment by ishaan812** [comment]
Hey was able to run it thanks for the advice. Are there any things I can help with as good first issues if you had some in mind?

**Comment by NektariosFifes** [comment]
@ishaan812 yes we could add support for mqtt

**Comment by ishaan812** [comment]
Yeah that would be great, I'll just wait till you merge and then we can decide what to do. I'm probably going to be inactive for the next 2 days. A meetup later this week works.

**Comment by Shurtu-gal** [comment]
Hey, @NektariosFifes can I work on this issue?

**Comment by NektariosFifes** [comment]
@Shurtu-gal hello sorry for not responding i have been busy lately and will soon start focusing on this project more as it is part of the mentorship program. We will arrange a meeting with people that are interested.

**Comment by NektariosFifes** [comment]
@Shurtu-gal here is a discord i made for the repository https://discord.gg/6wa9aHKB

**Comment by Shurtu-gal** [comment]
Thanks
